name = "passage-api"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "passage-index"

[[kv_namespaces]]
binding = "CACHE"
id = "8ef35f27790e4ab0a4d8932ff344126a"

[[r2_buckets]]
binding = "TEXTS"
bucket_name = "passage-texts"
